name: Assignment-09-SNS

on:
  push:
    branches: [ assignment-09 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Building Jar file
      run: mvn package

    - name: Checking AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Printing the contents of Directory before Packer build
      run: ls -l

    - name: Pushing Artifact to S3
      run: | 
        aws s3 sync target/serverlessLambda.jar s3://${{ secrets.S3_LAMBDA_BUCKET }}