name: Lambda-Serverless-Main-Push

env:
  ARTIFACT_NAME: serverlessLambda-${{ github.sha }}.jar

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Building Jar file
      run: mvn clean install package

    - name: Checking AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Printing the contents of Directory before Packer build
      run: ls -l

    - name: Pushing Artifact to S3
      run: |
        cp target/serverlessLambda.jar target/${{ env.ARTIFACT_NAME }}
        aws s3 cp target/${{ env.ARTIFACT_NAME }} s3://${{ secrets.S3_LAMBDA_BUCKET }}
    
    - name: Displaying contents of target folder
      working-directory: target
      run: ls -l

    - name: Update lambda function
      run: |
        aws lambda update-function-code --publish --function-name EmailVerificationLambda --s3-bucket ${{ secrets.S3_LAMBDA_BUCKET }} --s3-key ${{ env.ARTIFACT_NAME }}
